# GitHub Actions Workflow Update for Snepilatch (Android-only)
# Add these steps to your existing workflow, replacing the relevant sections

name: Build and Release Flutter Apps

on:
  push:
    tags:
      - 'v*'

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.x'
          channel: 'stable'
          cache: true

      - name: Setup release keystore
        working-directory: ./snepilatch/android
        env:
          KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: |
          echo "Setting up release keystore from secrets..."
          if [ -n "$KEYSTORE_BASE64" ]; then
            echo "Using existing keystore from secrets"
            echo "$KEYSTORE_BASE64" | base64 -d > app/snepilatch-release.keystore
          else
            echo "ERROR: No keystore found in secrets!"
            exit 1
          fi

      - name: Create key.properties
        working-directory: ./snepilatch/android
        env:
          KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: |
          echo "Creating key.properties file..."
          cat > key.properties << EOF
          storePassword=$KEYSTORE_PASSWORD
          keyPassword=$KEY_PASSWORD
          keyAlias=snepilatch
          storeFile=snepilatch-release.keystore
          EOF

      - name: Get dependencies
        working-directory: ./snepilatch
        run: flutter pub get

      - name: Build Android APK
        working-directory: ./snepilatch
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        run: |
          # Extract version without 'v' prefix
          VERSION="${{ github.ref_name }}"
          VERSION="${VERSION#v}"

          flutter build apk --release \
            --flavor prod \
            --build-name="$VERSION" \
            --build-number="${{ github.run_number }}" \
            --dart-define=SENTRY_DSN="$SENTRY_DSN" \
            --dart-define=SENTRY_RELEASE="$VERSION" \
            --dart-define=SENTRY_ENVIRONMENT="production"

      - name: Prepare artifacts
        working-directory: ./snepilatch
        run: |
          mkdir -p artifacts
          cp build/app/outputs/flutter-apk/app-prod-release.apk artifacts/snepilatch-${{ github.ref_name }}.apk

      - name: Upload Android artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: snepilatch/artifacts/

      - name: Upload Assets to Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            snepilatch/artifacts/snepilatch-${{ github.ref_name }}.apk
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}